### PR TITLE
Join the defaults rule for default settings, and get the parameters for successful verification

### PR DESCRIPTION
**Pull request by zw2582**
Join the defaults rule for default settings, and get the parameters for successful verification

### CODE REVIEW

**Comment by emsifa** [comment]
It is nice idea. But by looking on your code, I think it would cause an unexpected result, because you just set `validata`, and not using those default values for rule checking.

And I think `getValidata` is not good for naming and also can be miss understanding because it returns all validated data including invalid data. It should be named `getValidatedData`.

Or we can separate valid data and invalid data by set them after finish checking an attribute.

Let me know if you need help for this :wink:

**Comment by zw2582** [comment]
Yes, I have looked for a lot of validator frameworks. Your is the best, however, the default rule is missing, and the validated parameters cannot be obtained.This is very important and convenient because it can filter out some unsafe paramters, If possible, I hope you use your way to perfect this one

**Comment by zw2582** [comment]
In my scene, I don't need to separate valid data and invalid data. Because all data is valid data if validation is pass, If failed, I don't need any

**Comment by emsifa** [comment]
I just fix `defaults` functionality and add 3 methods:

* `getValidatedData()`: get all validated data.
* `getValidData()`: get only valid data.
* `getInvalidData()`: get only invalid data.

I will write documentation for it soon.

**Comment by zw2582** [comment]
ok

**Pull request merged**
