### PR TITLE
Feature: Array Validation

### PR DESCRIPTION
**Pull request by emsifa**
[WIP] Array validation. Now we can validate array like [Laravel 5.3](https://laravel.com/docs/5.3/validation#validating-arrays)

#### Update Notes

* Rename `setParamaters` to `fillParameters`  in `Rule` class (https://github.com/rakit/validation/pull/16/commits/2048b6c51dac7c730c6b163e73cc9385796261aa).
* Adding `setParameter` and `setParameters` methods to directly set parameter in rule instance (https://github.com/rakit/validation/pull/16/commits/f2ebdc0b88b66647398871bb7546e9e3fa004940).
* Adding property `primaryAttribute` and `otherAttributes` in `Attribute` class. So we can retrieve them in rule that need them (like [laravel distinct rule](https://laravel.com/docs/5.3/validation#rule-distinct))  using `getOtherAttributes()` and `getPrimaryAttribute()`  (https://github.com/rakit/validation/pull/16/commits/f3add9f4cd1a693e535cf96b28121a107efc4d3c).
* Custom message and rule name now separated by ':' instead '.' to distinguish with array attribute separator (https://github.com/rakit/validation/pull/16/commits/9fe41626a3cd6faac4dad8f0cc6535cb97f415a3). 
* `ErrorBag::get` now return array (https://github.com/rakit/validation/pull/16/commits/31508dce707073a3067a0168bd48cf36c9d5d5be).
 * Getting error for specified rule message in each attribute now using `first` method. Eg `$errors->first('age:numeric')` to retrieve `numeric` message in attribute `age` (https://github.com/rakit/validation/pull/16/commits/31508dce707073a3067a0168bd48cf36c9d5d5be).
* Adding `ErrorBag::has` method (https://github.com/rakit/validation/pull/16/commits/31508dce707073a3067a0168bd48cf36c9d5d5be).
* `ErrorBag::last` removed (https://github.com/rakit/validation/pull/16/commits/31508dce707073a3067a0168bd48cf36c9d5d5be).
* `ErrorBag::lastOfAll` removed (https://github.com/rakit/validation/pull/16/commits/31508dce707073a3067a0168bd48cf36c9d5d5be).

### CODE REVIEW

**Comment by adelowo** [comment]
Would test this out

**Comment by emsifa** [comment]
I will merge this soon. I wanted to check a few things about code efficiency. 

All updates are described in first comment.

**Comment by adelowo** [comment]
Oh cool.. To be honest, i cannot even go through the code right now, all i had was run the `tests`.

**Comment by emsifa** [comment]
Its ok @adelowo, you can contribute just if you can. I just want to save and give some information on this PR :smiley:

**Pull request merged**
