### PR TITLE
Update SizeTrait.php

### PR DESCRIPTION
**Pull request by jaystream**
is_float should be is_numeric to recognize the numeric string as number

### CODE REVIEW

**Comment by emsifa** [comment]
Laravel Validation treat this with different approach. If field/attribute has numeric/integer rule, they count its size by numeric value, and otherwise.

For example:

```php
$validation = $validator->validate([
    'number' => '1.23456789'
], [
    'number' => 'max:2'
]);
```

In this case, the `number` attribute will be invalid because they treat its value as a string.

But this example will be valid:

```php
$validation = $validator->validate([
    'number' => '1.23456789'
], [
    'number' => 'numeric|max:2'
]);
```

Because now they treat its value as numeric.

We can do same approach by checking if attribute has `numeric` rule with `getAttribute()->hasRule('numeric')`, and cast value to float before counting value's size.

**Comment by jaystream** [comment]
Hi @emsifa ,

Thank you for your response but this is what I am trying to do.
`$validation = $validator->validate([
    'number' => '11'
], [
    'number' => 'integer|min:10'
]);`
That will result a validation error `The Number minimum is 10` because the input value will be recognize as string and it will count the number of string.

Even on your example if I put it like:
`$validation = $validator->validate([
    'number' => '1.2'
], [
    'number' => 'numeric|max:2'
]);`
This will result a validation error of `The Number maximum is 2` even if the given input is `1.2`.

In this kind of scenario, do you have a different approach aside of placing an `(int)` before the given input?

**Comment by emsifa** [comment]
Yes this is not implemented yet. I would think a better way to achieve this later, maybe add an interface to flag a rule class that has it's own size counter, so custom rule can achieve the same functionality.

For now, could you modify `SiteTrait.php`  in this PR to achieve approach that I mentioned? I will merge it.

I'm thinking of something like this in `SizeTrait.php` before checking its type and returning its size:

```php
if ($this->getAttribute()->hasRule('numeric') && is_numeric($value)) {
    $value = (float) $value;
}
```

**Comment by jaystream** [comment]
Hi @emsifa ,
I just added that code.

**Pull request merged**
