### PR TITLE
Updated the uploaded rule to make use of a built in function

### PR DESCRIPTION
**Pull request by adelowo**

### CODE REVIEW

**Comment by emsifa** [comment]
Check this @adelowo, maybe I'm missing something

**Comment by emsifa** [comment]
I have manually test this with [code here](https://gist.github.com/emsifa/ba24b099caf2955283460cad91d5f61f), and it seems works properly.

**Comment by adelowo** [comment]
Sorry for the late reply..Like i said the other time. I have been extremely busy

**Comment by emsifa** [comment]
Its ok @adelowo :smiley:

**Pull request merged**
